spring.application.name=deepwork-ai
server.port=8081

# ---- DATABASE ----
spring.datasource.url=jdbc:postgresql://dpg-d7h87j1o3t8c73988n8g-a/deepwork_ai_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.username=deepwork_ai_db_user
spring.datasource.password=DxbvQl3VWnOyIXIfJrwnZfpEu7NC4Vey

# ---- JPA ----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---- FILE UPLOAD ----
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# ---- TIMEOUTS ----
server.tomcat.connection-timeout=600000
spring.mvc.async.request-timeout=600000

# Allow Vercel origin explicitly
cors.allowed-origins=https://deepwork-ai-one.vercel.app

ai.service.url=https://ameera09-ai-service.hf.space/analyze