spring.application.name=deepwork-ai
server.port=8081

# ---- DATABASE ----
spring.datasource.url=jdbc:mysql://localhost:3306/deepwork_ai
spring.datasource.username=root
spring.datasource.password=0000


# ---- JPA ----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---- FILE UPLOAD ----
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# ---- TIMEOUTS ----
server.tomcat.connection-timeout=600000
spring.mvc.async.request-timeout=600000

# Allow Vercel origin explicitly
cors.allowed-origins=https://deepwork-ai-one.vercel.app

ai.service.url=https://ameera09-ai-service.hf.space/analyze